const swaggerAutogen = require('swagger-autogen');
const doc = {
    info: {
        version: '1.0.0',
        title: 'ToDo Creation API',
        description: 'Documentation generated by swagger-autogen'
    },
    host: 'localhost:3000',
}

const outputFile = './swagger-output.json';
const endpointFiles = [ './app.js' ];

swaggerAutogen(outputFile, endpointFiles, doc).then(() => {
    require('./bin/www');
})